// <auto-generated />
using FinalPrepMission6And7CRUD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalPrepMission6And7CRUD.Migrations
{
    [DbContext(typeof(DateApplicationContext))]
    [Migration("20230424201805_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("FinalPrepMission6And7CRUD.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CreeperStalker")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("MajorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationId");

                    b.HasIndex("MajorId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Age = (byte)45,
                            CreeperStalker = true,
                            FirstName = "Michael",
                            LastName = "Scott",
                            MajorId = 4,
                            Phone = "555-555-5555"
                        },
                        new
                        {
                            ApplicationId = 2,
                            Age = (byte)33,
                            CreeperStalker = false,
                            FirstName = "John",
                            LastName = "Hills",
                            MajorId = 5,
                            Phone = "444-555-5555"
                        });
                });

            modelBuilder.Entity("FinalPrepMission6And7CRUD.Models.Major", b =>
                {
                    b.Property<int>("MajorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MajorName")
                        .HasColumnType("TEXT");

                    b.HasKey("MajorId");

                    b.ToTable("Majors");

                    b.HasData(
                        new
                        {
                            MajorId = 1,
                            MajorName = "Information Systems"
                        },
                        new
                        {
                            MajorId = 2,
                            MajorName = "Ancient Near Eastern Studies"
                        },
                        new
                        {
                            MajorId = 3,
                            MajorName = "Accounting"
                        },
                        new
                        {
                            MajorId = 4,
                            MajorName = "Actuarial Science"
                        },
                        new
                        {
                            MajorId = 5,
                            MajorName = "Undeclared"
                        });
                });

            modelBuilder.Entity("FinalPrepMission6And7CRUD.Models.ApplicationResponse", b =>
                {
                    b.HasOne("FinalPrepMission6And7CRUD.Models.Major", "Major")
                        .WithMany()
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
